
project_id = "gqlkritspnhjxfejvgfg"

[functions.create-daily-room]
verify_jwt = true

[functions.generate-clinical-note]
verify_jwt = true

[functions.getavailabilitysettings]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.nylas-events]
verify_jwt = true

[functions.nylas-auth]
verify_jwt = true

[functions.nylas-sync-appointments]
verify_jwt = true

[functions.nylas-scheduler-config]
verify_jwt = true

[functions.appointment-reminder-emails]
verify_jwt = false

[functions.appointment-reminder-eastern]
verify_jwt = false

[functions.appointment-reminder-central]
verify_jwt = false

[functions.appointment-reminder-mountain]
verify_jwt = false

[functions.appointment-reminder-pacific]
verify_jwt = false

[functions.appointment-reminder-alaska]
verify_jwt = false

[functions.appointment-reminder-hawaii]
verify_jwt = false

[functions.appointment-reminder-arizona]
verify_jwt = false
