
project_id = "gqlkritspnhjxfejvgfg"

[functions.create-daily-room]
verify_jwt = true

[functions.getavailabilitysettings]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.nylas-auth]
verify_jwt = true

[functions.nylas-sync-appointments]
verify_jwt = true

[functions.nylas-scheduler-config]
verify_jwt = true
