
project_id = "gqlkritspnhjxfejvgfg"
[functions.create-daily-room]
verify_jwt = true
[functions.getavailabilitysettings]
verify_jwt = true
[functions.list-users]
verify_jwt = true
[functions.delete-user]
verify_jwt = true
