
name: Deploy Nylas Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Supabase CLI
      run: |
        npm install -g supabase
    
    - name: Deploy Nylas Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: gqlkritspnhjxfejvgfg
      run: |
        supabase login --token $SUPABASE_ACCESS_TOKEN
        supabase functions deploy nylas-auth --project-ref $SUPABASE_PROJECT_ID
        supabase functions deploy nylas-events --project-ref $SUPABASE_PROJECT_ID
        supabase functions deploy nylas-sync-appointments --project-ref $SUPABASE_PROJECT_ID
        supabase functions deploy nylas-scheduler-config --project-ref $SUPABASE_PROJECT_ID
        echo "✅ All Nylas functions deployed successfully!"
